README.md
tes.java

Penambahan gif dan tata ulang teks file readme.md

UPDATE: README.md

---

SistemAtm.java

Penambahan komentar untuk menjelaskan step/alur kerja dari source code yang dibuat dan menambahkan penulisan format output dalam Rupiah

UPDATE: penambahan komentar dan format rupiah

---

SistemAtm.java

Penambahan fitur pembayaran lain-lain. Salah satunya adalah pembayaran pulsa

UPDATE: penambahan fitur pembayaran lain (pulsa)

---

SistemAtm.java

Perbaikan beberapa baris kode yang bermasalah

UPDATE: koreksi line code

---

SistemAtm.java

Perbaikan tampilan riwayat transaksi menjadi lebih mantap !

UPDATE: perbaikan tampilan riwayat transaksi

---

SistemAtm.java

Penambahan fitur pembayaran tagihan listrik pada pembayaran lain-lain. Namun, masih ada sedikit kekurangan yaitu ketika pengguna menginputkan ID PLN tidak sesuai dengan data, masih belum dibuat skenarionya.
@sukinnamz @AtabikM1

UPDATE: penambahan fitur pembayaran tagihan listrik

---

SistemAtm.java

@sukinnamz @AtabikM1 
Fitur pembayaran listrik telah fix (tuntas)

UPDATE: perbaikan fitur pembayaran tagihan listrik

---

SistemAtm.java

Fix input TF

---

ATM_INTERFACE.java
SistemAtm.java

Perbaikan minor mengenai penamaan variabel dan beberapa perubaahn pada fitur transfer. Secara keseluruhan tidak ada perubahan yang begitu berarti

UPDATE: perbaikan nama variabel dan penyempurnaan fitur transfer

---

SistemAtm.java

UPDATE: perbaikan fitur tarik tunai

---

SistemAtm.java

Saya menemukan masalah pada fitur transfer. Masalanya adalah jika user telah input nomor rekening, kemudian pada tahapan selanjutnya nilainya false. C
- Contoh kasus: Ketika user input nomor rekening dengan benar. Kemudian user input nominal transfer melebihi ketentuan, maka user akan bisa mengulangi tahapan transfer. 
**MASALAH DIMULAI**
Ketika user input nomor rekening tujuan lagi. Namun input tersebut tidak sesuai dengan database, maka user tetap bisa melanjutkan proses berikutnya. PADAHAL, user seharusnya tidak bisa melakukan itu. 
Saya menemukan titik masalahnya yaitu **TIDAK MENGEMBALIKAN NILAI VARIABEL isValid** yang awalnya TRUE menjadi FALSE. Ini membuat kondisi seperti yang saya ceritakan sebelumnya. Apapun input yang diberikan oleh user itu akn dianggap TRUE oleh komputer. …

UPDATE: tampilan sistem dan perbaikan fitur transfer

---

SistemAtm.java

Perubahan yang saya lakukan adalah proses pengecekan apakah nominal transfer kurang dari saldo pengguna dilakukan setelah pengguna input PIN. Jadi pengguna bisa transfer dengan nominal berapapun di awal tanpa mengetahui apakah saldonya itu cukup atau tidak.
-Farrel AD

UPDATE: perubahan alur kerja fitur transfer

---

SistemAtm.java

Perubahan tampilan menjadi mengkeren!

UPDATE: pembaruan tampilan fitur setor dan tarik tunai

---

SistemAtm.java

Kali ini tampilan pembayaran pulsa menjadi lebih bagus

UPDATE: perbaikan fitur pembayaran pulsa dan perubahan tampilan

---

SistemAtm.java

UPDATE: perubahan tampilan dan perbaikan fitur pembayaran tagihan listrik

---

SistemAtm.java

UPDATE: perubahan tampilan fitur pembayaran tagihan pendidikan

---

SistemAtm.java

perubahan kecil pada output yang ditampilkan pada fitur ubah PIN

UPDATE: perubahan minor tampilan fitur UBAH PIN

---

SistemAtm.java

pdam update variable

---

SistemAtm.java

still BPJS

---

SistemAtm.java

Penambahan fitur keluar dan perbaikan pada fitur ubah PIN

Fitur 'keluar' dan fitur 'ubah PIN'

---

SistemAtm.java

Perbaikan nama variabel kecuali pada fitur pembayaran lainnya.

fix: perbaikan nama variabel agar lebih jelas

---

SistemAtm.java

Perbaikan fitur transfer menjadi tidak bisa transfer ke rekening diri sendiri

fix: fitur transfer - perbaikan tujuan rekening

---

SistemAtm.java

perbaikan penamaan variabel pada fitur transfer, tarik tunai, dan setor tunai

fix: fitur transfer, tarik, setor tunai - variabel

---

SistemATM.java

Perubahan penamaan dari 'public class SistemAtm' menjadi 'public class SistemATM'

fix: penamaan kelas utama sesuai dengan nama file

---

SistemATM.java

Perbaikan kecil pada bagian penamaan variabel dan perbaikan komentar pada fitur pembayaran lainnya

update minor fitur pembayaran lainnya

---

SistemATM.java

Penambahan elemen flush, yaitu elemen yang bisa menghilangkan output yang telah dicetak ke layar. Ini berfungsi untuk memudahkan pengguna melihat menu yang tersedia

Penambahan elemen flush pada beberapa fitur

---

SistemATM.java

Penambahan elemen flush pada fitur ubah pin, bayar listrik, bayar pendidikan, bayar pdam, dan bayar bpjs

Penambahan elemen flush pada beberapa fitur  di pembayaran lainnya

---

Function000SistemATM.java

tambah fungsi ClearScreen. Tujuan: untuk menghapus output yang telah ditampilkan ke layar

feat: fungsi ClearScreen

---

Function000SistemATM.java

Mengisi tugas yang bisa dieksekusi oleh fungsi Exit dan menambahkan fungsi baru yaitu ClearScreen

Tambah fungsi Exit dan ClearScreen

---

Function000SistemATM.java

Menambahkan tampilan pada setiap menu yang dipilih

Tambah fungsi 'view' pada setiap menu

---

Function000SistemATM.java

Menambahkan fungsi 'view' berupa hiasan pada setiap submenu yang ada di fitur pembayaran lainnya

Tambah fungsi 'view' pada submenu pembayaran lainnya

---

Function000SistemATM.java

Perbaikan alur kerja fitur login yang memungkinkan pengguna untuk tetap bisa bertransaksi meskipun nomor rekening telah diblokir. Dengan catatan, login dengan nomor rekening selain yang telah diblokir
INFO UPDATE: @sukinnamz @AtabikM1

Perbaikan alur kerja fitur login

---

Function000SistemATM.java

Menambahkan fungsi untuk digunakan sebagai validasi PIN. Pada setiap transaksi biasanya pengguna diharuskan untuk input PIN. Untuk menyederhanakan source code, maka dibuatlah fungsi PinValidation.

feat: tambah fungsi PinValidation

---

Function000SistemATM.java

Menambahkan fungsi konfirmasi transaksi dengan nama TransactionConfirmation. Ini membuat kode program yang memperlukan konfirmasi pembayaran/transaksi, maka bisa lebih efisien karena hanya tinggal memanggil fungsi ini

feat: tambah fungsi TransactionConfirmation

---

Function000SistemATM.java

Tujuan: pada beberapa bagian di fitur memerlukan adanya input perintah (enter misalnya) untuk mencegah fungsi ClearScreen terus berjalan. 
Input: klik enter
output: ketika pengguna klik enter (sebenarnya bisa klik selain enter karena tidak ada pengecekan nilainya), maka perintah program selanjutnya akan dijalankan

feat: tambah fungsi EnterForContinue

---

Function000SistemATM.java

Perubahan nama fungsi TransactionConfirmation menjadi UserConfirmation. Penamaan TransactionConfirmation saya rasa kurang tepat karena fungsi konfirmasi ini tidak hanya untuk transaksi saja. Kadang juga digunakan untuk non-transaksi seperti pada fitur Exit

Perubahan nama fungsi TransactionConfirmation

---

Function000SistemATM.java

Sebelum ada update, jika pengguna melakukan transaksi lebih dari 10, maka fitur riwayat transaksi tidak akan bisa bekerja dengan baik. Sekarang sudah saya update dengan mengganti yang tadinya array biasa menjadi array list. Dengan adanya ini bisa mudah mengisi nilai pada array serta bisa menghapusnya dengan lebih mudah 
@sukinnamz @AtabikM1

fix: perbaikan riwayat transaksi jika sudah melebihi 10 value

---

ATMSystem.java

Sempat mengalami masalah yaitu fungsi input PIN dan fungsi EnterForContinue sempat ter-_skip_ pada bagian scanner. Sudah saya perbaiki dengan menggunakan scanner yang lainnya

fix: perbaikan eror pada input PIN dan fungsi EnterForContinue

---

ATMSystem.java

Fitur bantuan ini masih belum sempurna. Saya hanya menambahkan keterangan singkat mengenai cara mengoperasikan program.

feat: tambah fitur help/bantuan di dalam menu

---

ATMSystem.java

Perbaikan penyusunan code menjadi lebih efisien lagi

fix: perbaikan code pada fitur konfirmasi menu dan closing

---

ATMSystem.java

Tampilan dari fitur transfer sudah banyak berubah. Sekarang bisa tampil dengan lebih rapi ditambah dengan fitur multibahasa yang tetap berjalan

fix: perbaikan tampilan dan mekanisme fitur transfer
